# Generated by Django 4.1.3 on 2022-11-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TodoItem",
            new_name="Task",
        ),
    ]
